morph

diff --git a/build b/build
--- a/build
+++ b/build
@@ -136,15 +136,16 @@ else
     fi
 
     if [ ! -e opencv ] ; then
-      git clone https://github.com/firepick1/opencv -b 2.4
+      sudo -u $SUDO_USER git clone https://github.com/firepick1/opencv -b 2.4
     fi
     mkdir opencv/build
     pushd opencv/build
-      cmake \
+      sudo -u $SUDO_USER cmake \
 	-D WITH_OPENEXR=OFF \
         -D CMAKE_BUILD_TYPE=DEBUG \
 	-D CMAKE_INSTALL_PREFIX=/usr/local \
         ..
+      sudo -u $SUDO_USER
       make install
     popd
 fi
@@ -152,11 +153,7 @@ fi
 if [ -e CMakeFiles ] ; then 
   echo removing existing makefiles
   rm -rf CMakeCache.txt CMakeFiles CMakeFiles.txt target cmake_install.cmake CPackConfig.cmake CPackSourceConfig.cmake
-  if [ "$SUDO_USER" == "" ] ; then
-    mkdir target
-  else 
-    sudo -u $SUDO_USER mkdir target
-  fi
+  sudo -u $SUDO_USER mkdir target
 fi
 
 
@@ -165,9 +162,11 @@ sudo -u $SUDO_USER cmake \
   -DCMAKE_INSTALL_PREFIX:PATH=$installPrefix "$@" \
   .
 echo building and installing FireSight...
+sudo -u $SUDO_USER make
 make install
-if [ $? -eq 0 ]; then
-  echo HAPPINESS AND JOY...
-else
-  echo SADNESS AND TEARS...
+if [ $? -ne 0 ]; then
+  echo "ERROR: make failed"
+  exit -1
 fi
+
+echo "Installation complete: firesight"
